name: frontend semgrep

on:
  workflow_call:
    outputs:
      length:
        value: ${{ jobs.analyze-report.outputs.length }}
      reject:
        value: ${{ jobs.analyze-report.outputs.reject }}
      latestsarif:
        value: ${{ jobs.analyze-report.outputs.latestsarif }}
      finding:
        value: ${{ jobs.analyze-report.outputs.finding }}
      message:
        value: ${{ jobs.analyze-report.outputs.message }}
      capitalized:
        value: ${{ jobs.analyze-report.outputs.capitalized }}

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: CheckoutðŸ›Žï¸
        uses: actions/checkout@v4
      - name: Create Command
        id: create-command
        run: |
          config=$(cat ./devtools/semgrep/semgrep-frontend.config|tr '\n' ' '|sed -e 's/ $/\n/g')
          semgrep_command_args=$(echo "scan $config ./frontend --sarif --output ./frontend/frontend.sarif")
          echo "args=$(echo $semgrep_command_args)" >> "$GITHUB_OUTPUT"
      - name: ScanðŸŒˆ
        id: scan
        uses: docker://returntocorp/semgrep:1.48.0
        with:
          entrypoint: "semgrep"
          args: ${{ steps.create-command.outputs.args }}
      - name: Upload ReportðŸ“‘
        uses: actions/upload-artifact@v3
        with:
          name: semgrep frontend report
          path: |
            ./frontend/frontend.sarif
            ./devtools/semgrep/semgrep-rule-info-generation.sh
            ./devtools/semgrep/semgrep-report-generation.sh
  analyze-report:
    name: Analyze Report
    needs: semgrep
    uses: ./.github/actions/semgrep-report.yaml
    with:
      location: frontend
      descriptionKey: .fullDescription.text
