name: 0_push_back_fakes

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "backend/FakesAssemblies/**"

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - run: echo "do 0_push_back_fakes"
