name: 1_back_csproj

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      OWNER_ACCESS_TOKEN:
        required: true
    outputs:
      comment:
        value: ${{ jobs.license_check.outputs.result }}

jobs:
  license_check:
    uses: ./.github/workflows/2_back_license.yaml
    with:
      solution_directory: backend/NeuroFramework.Common
    secrets:
      OWNER_ACCESS_TOKEN: ${{ secrets.OWNER_ACCESS_TOKEN }}
