name: 1_front

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      comment:
        value: ${{ jobs.create_omment.outputs.comment }}

jobs:
  semgrep:
    name: Frontend Semgrep✅
    uses: ./.github/workflows/frontend-semgrep.yaml

  create_omment:
    runs-on: ubuntu-latest
    needs: semgrep
    if: ${{ !cancelled() }}
    outputs:
      comment: ${{ steps.comment.outputs.comment }}
    steps:
      - id: comment
        run: |
          comment="${{ needs.semgrep.outputs.result }}"
          echo "comment=${comment}" > "$GITHUB_OUTPUT"
