name: 1_front

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      REPO_ACCESS_TOKEN:
        required: true
    outputs:
      comment:
        value: ${{ jobs.semgrep.outputs.comment }}

jobs:
  semgrep:
    uses: ./.github/workflows/2_semgrep.yaml
    with:
      location: frontend
      path: frontend
    secrets:
      REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
