name: 1_front_pnpm

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      comment:
        value: ${{ jobs.license_check.outputs.result }}

jobs:
  license_check:
    uses: ./.github/workflows/2_front_license.yaml
