name: 1_front

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      OWNER_ACCESS_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true
    outputs:
      comment:
        value: ${{ jobs.semgrep.outputs.comment }} \n\n ${{ jobs.sonaqube.outputs.comment }}

jobs:
  semgrep:
    uses: ./.github/workflows/2_semgrep.yaml
    with:
      location: frontend
      path: frontend
    secrets:
      OWNER_ACCESS_TOKEN: ${{ secrets.OWNER_ACCESS_TOKEN }}
  sonarqube:
    uses: ./.github/workflows/2_front_sonarqube.yaml
    with:
      solution_directory: frontend
      sonar_project: nfw-common-frontend
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
