name: 2_nuget_publish_common

on:
  workflow_call:
    secrets:
      OWNER_ACCESS_TOKEN:
        required: true

env:
  GITHUB_ACCOUNT: ${{ github.repository_owner }}
  GITHUB_PKG_NFW_AUTH_TOKEN: ${{ secrets.OWNER_ACCESS_TOKEN }}

jobs:
  version_increment:
    uses: ./.github/workflows/2_version_increment.yaml
    with:
      version_fragment: "alpha"

  publish:
    runs-on: windows-latest
    needs: version_increment

    steps:
      - name: 💼 Checkout
        uses: actions/checkout@v4

      - name: ⚡ Setup Nuget Cache
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: 🖥️ Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: ⚒️ Build
        run: |
          cd .\backend\NeuroFramework.Common
          dotnet restore --configfile "github-actions-nuget.config"
          msbuild -m -p:Configuration=Release -p:IsGithubActions=true -verbosity:quiet -p:Version=${{ needs.version_increment.outputs.next }}

      - name: 🎁 Publish
        uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with:
          nupkg-path: '.\backend\NeuroFramework.Common\src\**\bin\Release\*.nupkg'
          repo-owner: ${{ github.repository_owner }}
          gh-user: ${{ github.repository_owner }}
          token: ${{ secrets.OWNER_ACCESS_TOKEN }}
