name: 2_post_comment

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      comment:
        required: true
        type: string

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        env:
          title: ${{ inputs.title }}
          comment: ${{ inputs.comment }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const env = process.env;
            const body = `## ${env.title}\n\n${env.comment}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })
