name: 2_post_comment

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      comment:
        required: true
        type: string

jobs:
  post_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `## ${{ inputs.title }}\n\n${{ inputs.comment }}`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })
