name: 2_semgrep_create_comment

on:
  workflow_call:
    inputs:
      length:
        required: true
        type: string
      location:
        required: true
        type: string
      findings:
        required: true
        type: string
      message:
        required: true
        type: string
    outputs:
      comment:
        value: ${{ jobs.create_comment.outputs.comment }}

jobs:
  create_comment:
    runs-on: ubuntu-latest
    outputs:
      comment: ${{ steps.comment.outputs.result }}
    steps:
      - name: Generate Findings Table
        if: ${{ inputs.findings != '' }}
        uses: buildingcash/json-to-markdown-table-action@v1
        id: findings_table
        with:
          json: ${{ inputs.findings }}

      - name: Generate Message Table
        if: ${{ inputs.length > 0 }}
        uses: buildingcash/json-to-markdown-table-action@v1
        id: message_table
        with:
          json: ${{ inputs.message }}

      - name: Create Comment
        if: always()
        uses: actions/github-script@v7
        id: comment
        with:
          script: |
            result="### 📄${{ inputs.location }} Semgrep Analysis\n\n"
            if [ ${{ inputs.length > 0 }} == '' ]; then
              result+="✅Congratulations! There is no findings\n\n"
            else
              result+="#### Summary Table\n\n${{ steps.findings_table.outputs.table }}\n\n"
              result+="#### Findings\n\n${{ steps.message_table.outputs.table }}\n\n"
            fi
            return result
