name: 2_semgrep_create_comment

on:
  workflow_call:
    inputs:
      length:
        required: true
        type: string
      location:
        required: true
        type: string
      findings:
        required: true
        type: string
      message:
        required: true
        type: string
    outputs:
      comment:
        value: ${{ jobs.create_comment.outputs.comment }}

jobs:
  create_comment:
    runs-on: ubuntu-latest
    outputs:
      comment: ${{ steps.comment.outputs.result }}
    steps:
      - name: Generate Findings Table
        if: ${{ inputs.findings != '' }}
        uses: buildingcash/json-to-markdown-table-action@v1
        id: findings_table
        with:
          json: ${{ inputs.findings }}

      - name: Generate Message Table
        if: ${{ inputs.length > 0 }}
        uses: buildingcash/json-to-markdown-table-action@v1
        id: message_table
        with:
          json: ${{ inputs.message }}

      - name: Create Comment
        if: always()
        uses: actions/github-script@v7
        id: comment
        env:
          LOCATION: ${{ inputs.location }}
          LENGTH: ${{ inputs.length }}
          FINDINGS: ${{ steps.findings_table.outputs.table }}
          MESSAGE: ${{ steps.message_table.outputs.table }}
        with:
          script: |
            const env = process.env;
            let result = `### 📄${env.LOCATION} Semgrep Analysis\n\n`;
            if (env.LENGTH === 0) {
              result += "✅Congratulations! There is no findings\n\n";
            }else {
              result += `#### Summary Table\n\n${env.FINDINGS}\n\n`;
              result += `#### Findings\n\n${env.MESSAGE}\n\n`;
            }
            return result;
