name: comment on pull request

on:
  workflow_call:
    inputs:
      action_name:
        required: true
        type: string
      comment:
        required: true
        type: string

jobs:
  comment:
    runs-on: ubuntu-latest
    env:
      ACTIONS_NAME: ${{ inputs.action_name }}
      COMMENT: ${{ inputs.comment }}
    steps:
      - name: Create comments
        run: |
          touch comments
          echo "## ${ACTIONS_NAME}\\n" >> comments
          echo; >> comments
          echo -e ${COMMENT} >> comments

      - name: Post comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./comments "${URL}"
