name: Npm Publishment

on:
  workflow_call:
    inputs:
      frontend_dir_name:
        required: true
        type: string

env:
  GITHUB_ACCOUNT: ${{ secrets.REPO_ACCOUNT }}
  GITHUB_PKG_NFW_AUTH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

jobs:
  version-increment:
    uses: ./.github/workflows/version-increment.yaml
    with:
      version-fragment: alpha
      prefix: frontend-${{ inputs.frontend_dir_name }}-

  publish:
    runs-on: ubuntu-latest
    needs: version-increment
    defaults:
      run:
        working-directory: ./frontend/${{ inputs.frontend_dir_name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ">=18.2.0"
          registry-url: https://npm.pkg.github.com

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install node_modules
        run: pnpm i

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
