name: NuGet Publishment For FakesAssemblies

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    types: [closed]
    paths:
      - "backend/FakesAssemblies/**"

env:
  GITHUB_ACCOUNT: ${{  secrets.REPO_ACCOUNT  }}
  GITHUB_PKG_NFW_AUTH_TOKEN: ${{  secrets.REPO_ACCESS_TOKEN  }}

jobs:
  version-increment:
    uses: ./.github/workflows/version-increment.yaml
    with:
      version-fragment: "alpha"

  publish:
    runs-on: windows-latest
    needs: version-increment

    steps:
      - uses: actions/checkout@v4

      - name: Increasing Fakes Assemblies Version Number
        run: |
          $items = Get-ChildItem ".\backend\FakesAssemblies\**\*.nuspec"
          foreach ($item in $items) {
          $content=Get-Content $item
          $ret=[regex]::Matches($content,"version>(.*)<\/version")
          if($ret.Count -eq 0){
          continue
          }else{
          $content -replace $ret.Groups[1].Value,"${{ needs.version-increment.outputs.next }}" | Out-File $item
          }
          }

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build Fakes Assemblies
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd .\backend\FakesAssemblies
          dotnet restore
          msbuild /m /p:Configuration=Release -verbosity:quiet FakesAssemblies.sln

      - name: Publish Fakes Assemblies NuGet
        uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with:
          nupkg-path: '.\backend\FakesAssemblies\**\*.nupkg'
          repo-owner: "elon-max"
          gh-user: ${{  secrets.REPO_ACCOUNT  }}
          token: ${{  secrets.REPO_ACCESS_TOKEN  }}
