name: generate semgrep report

on:
  workflow_call:
    inputs:
      location:
        required: true
        type: string
      descriptionKey:
        required: true
        type: string
    outputs:
      result:
        value: ${{ jobs.comment_pr.outputs.comment }}

jobs:
  report:
    runs-on: ubuntu-latest
    outputs:
      length: ${{ steps.ruleinfo.outputs.length }}
      reject: ${{ steps.ruleinfo.outputs.reject }}
      latestsarif: ${{ steps.ruleinfo.outputs.latestsarif }}
      findings: ${{ steps.extract.outputs.findings }}
      message: ${{ steps.extract.outputs.message }}
      capitalized: ${{ steps.string.outputs.capitalized }}

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: semgrep ${{ inputs.location }} report
          path: semgrepreport/
      - name: Generate Rule Info For Semgrep Findings
        id: ruleinfo
        run: |
          cd ./semgrepreport/${{ inputs.location }}
          cp ${{ inputs.location }}.sarif ../devtools/semgrep/
          cd ../devtools/semgrep/
          location="${{ inputs.location }}" descriptionKey="${{ inputs.descriptionKey }}" bash semgrep-rule-info-generation.sh

      - name: Generate Semgrep Finding Report
        if: steps.ruleinfo.outputs.length > 0
        id: extract
        run: |
          cd ./semgrepreport/devtools/semgrep/
          latestsarif="${{ steps.ruleinfo.outputs.latestsarif }}" bash semgrep-report-generation.sh

      - name: Upper Location
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ inputs.location }}
  comment_pr:
    uses: ./.github/workflows/semgrep-table.yaml
    needs: report
    with:
      length: ${{ needs.report.outputs.length }}
      location: ${{ needs.report.outputs.capitalized }}
      findings: ${{ needs.report.outputs.findings }}
      message: ${{ needs.report.outputs.message }}

  judge-reject:
    needs: report
    if: needs.report.outputs.reject > 0
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
