name: Create Semgrep Table For PR

on:
  workflow_call:
    inputs:
      location:
        required: true
        type: string
      finding:
        required: true
        type: string
      message:
        required: true
        type: string

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Finding Table
        uses: buildingcash/json-to-markdown-table-action@v1
        id: findingtable
        with:
          json: ${{ inputs.finding }}

      - name: Generate Message Table
        uses: buildingcash/json-to-markdown-table-action@v1
        id: messagetable
        with:
          json: ${{ inputs.message }}

      - name: Comment PR(If Findings Exist)
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            # Semgrep(${{ inputs.location }}) 🛑
            Summary Table
            ${{ steps.findingtable.outputs.table }}

            Messages Of Findings
            ${{ steps.messagetable.outputs.table }}
