name: Create Semgrep Table For PR

on:
  workflow_call:
    inputs:
      length:
        required: true
        type: number
      location:
        required: true
        type: string
      findings:
        required: true
        type: string
      message:
        required: true
        type: string
    outputs:
      comment:
        value: ${{ jobs.comment.outputs.comment }}

jobs:
  comment:
    runs-on: ubuntu-latest
    outputs:
      comment: ${{ steps.comment.outputs.comment }}
    steps:
      - name: Generate Finding Table
        if: ${{ inputs.length > 0 }}
        uses: buildingcash/json-to-markdown-table-action@v1
        id: findingtable
        with:
          json: ${{ inputs.findings }}

      - name: Generate Message Table
        if: ${{ inputs.length > 0 }}
        uses: buildingcash/json-to-markdown-table-action@v1
        id: messagetable
        with:
          json: ${{ inputs.message }}

      - name: Create Comment
        id: comment
        run: |
          comment="### 📄${{ inputs.location }} Semgrep Analysis\n\n"
          if [ ${{ inputs.length }} -eq 0 ]; then
            comment+="✅Congratulations! There is no findings"
          else
          comment+="#### Summary Table\n\n${{ steps.findingtable.outputs.table }}\n\n"
          comment+="#### Findings\n\n${{ steps.messagetable.outputs.table }}"
          fi
          echo "comment=${comment}" > "$GITHUB_OUTPUT"
