name: unit test

on:
  workflow_call:
    secrets:
      REPO_ACCOUNT:
        required: true
      REPO_ACCESS_TOKEN:
        required: true

env:
  GITHUB_ACCOUNT: ${{  secrets.REPO_ACCOUNT  }}
  GITHUB_PKG_NFW_AUTH_TOKEN: ${{  secrets.REPO_ACCESS_TOKEN  }}

jobs:
  unit_test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1

      - name: Generate Unit Test Report
        run: |
          cd .\backend\NeuroFramework.Common
          dotnet restore -p:WarningsNotAsErrors=NU1603 -p:NoWarn=NU1603 --configfile "github-actions-nuget.config"
          msbuild /m /p:Configuration=Release -verbosity:quiet
          vstest.console.exe /platform:x64 /inIsolation /Blame /Logger:trx /Enablecodecoverage .\tests\NeuroFramework.*\bin\Release\net7.0\**.Tests.dll /collect:"Code Coverage;Format=Cobertura"

      - name: Test Report
        if: always()
        id: test-report
        uses: phoenix-actions/test-reporting@v8
        with:
          name: Unit Tests Report
          path: "./backend/NeuroFramework.Common/TestResults/**.trx"
          reporter: dotnet-trx
          fail-on-error: "true"
          only-summary: "false"
          list-suites: "all"
          list-tests: "all"

      #- name: Comment PR
      #  if: always()
      #  uses: thollander/actions-comment-pull-request@v2
      #  with:
      #    message: |
      #      Check The Unit Test Report: **${{ steps.test-report.outputs.runHtmlUrl }}**

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code coverage report
          path: .\backend\NeuroFramework.Common\TestResults\**\*.cobertura.xml

  code_coverage_report:
    needs: unit_test
    runs-on: ubuntu-latest
    name: code coverage report
    if: ${{ !cancelled() }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: code coverage report
          path: coveragereport/

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coveragereport/**/*.cobertura.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"

      #- name: Add Coverage PR Comment
      #  uses: marocchino/sticky-pull-request-comment@v2
      #  with:
      #    recreate: true
      #    path: code-coverage-results.md

  auto_reject:
    needs: unit_test
    uses: ./.github/workflows/auto-reject.yaml
    if: failure()
